begin;
\ir _helpers.psql
select plan(20);

select tests.create_user('ada@example.com') as ada \gset
select tests.create_user('bob@example.com') as bob \gset
select tests.create_document(:'ada') as doc \gset
select tests.create_document(:'bob') as bob_doc \gset

-- Quiz generated by the AI function (service role)
insert into public.quizzes (id, user_id, document_id, title, time_limit_seconds)
values ('00000000-0000-0000-0000-0000000000a1', :'ada', :'doc', 'Cells', 600);
insert into public.quiz_questions (id, quiz_id, user_id, position, type, prompt, choices, correct_answer) values
  ('00000000-0000-0000-0000-0000000000b1', '00000000-0000-0000-0000-0000000000a1', :'ada', 0, 'multiple_choice', 'Powerhouse of the cell?', array['Nucleus', 'Mitochondria', 'Ribosome'], 'Mitochondria'),
  ('00000000-0000-0000-0000-0000000000b2', '00000000-0000-0000-0000-0000000000a1', :'ada', 1, 'true_false', 'Plant cells have walls.', null, 'true'),
  ('00000000-0000-0000-0000-0000000000b3', '00000000-0000-0000-0000-0000000000a1', :'ada', 2, 'short_answer', 'Name the process plants use to make food.', null, 'Photosynthesis'),
  ('00000000-0000-0000-0000-0000000000b4', '00000000-0000-0000-0000-0000000000a1', :'ada', 3, 'short_answer', 'Why do cells divide?', null, 'Growth and repair');

select is((select question_count from public.quizzes where id = '00000000-0000-0000-0000-0000000000a1'), 4, 'question_count is maintained');

select throws_ok(
  format('insert into public.quiz_questions (quiz_id, user_id, position, type, prompt, choices, correct_answer) values (%L, %L, 9, %L, %L, %L, %L)',
    '00000000-0000-0000-0000-0000000000a1', :'ada', 'multiple_choice', 'Q', '{A,B}', 'C'),
  '23514', null, 'a multiple-choice answer must be one of the choices'
);
select throws_ok(
  format('insert into public.quiz_questions (quiz_id, user_id, position, type, prompt, correct_answer) values (%L, %L, 9, %L, %L, %L)',
    '00000000-0000-0000-0000-0000000000a1', :'ada', 'true_false', 'Q', 'maybe'),
  '23514', null, 'a true/false answer must be true or false'
);

set local role authenticated;
select tests.as_user(:'ada');

select public.start_quiz_attempt('00000000-0000-0000-0000-0000000000a1') as attempt \gset
select results_eq(
  format($$select * from public.submit_quiz_attempt(%L, %L)$$, :'attempt', jsonb_build_object(
    '00000000-0000-0000-0000-0000000000b1', 'mitochondria ',
    '00000000-0000-0000-0000-0000000000b2', 'false',
    '00000000-0000-0000-0000-0000000000b3', 'photosynthesis.',
    '00000000-0000-0000-0000-0000000000b4', 'To grow'
  )),
  $$values (2, 4, 1)$$,
  'objective answers are graded server-side, tolerant of case, spacing and punctuation'
);
select is(
  (select is_correct from public.quiz_answers where question_id = '00000000-0000-0000-0000-0000000000b4'),
  null, 'a free-text answer that does not match exactly is left for AI grading'
);
select throws_ok(
  format($$select * from public.submit_quiz_attempt(%L, '{}')$$, :'attempt'),
  '22023', null, 'an attempt cannot be submitted twice'
);
select throws_ok(
  $$insert into public.quiz_attempts (quiz_id, user_id) values ('00000000-0000-0000-0000-0000000000a1', auth.uid())$$,
  '42501', null, 'clients cannot write attempts directly'
);

select tests.as_user(:'bob');
select throws_ok(
  format($$select * from public.submit_quiz_attempt(%L, '{}')$$, :'attempt'),
  'P0002', null, 'another user cannot submit my attempt'
);
select throws_ok(
  $$select public.start_quiz_attempt('00000000-0000-0000-0000-0000000000a1')$$,
  'P0002', null, 'another user cannot start my quiz'
);

-- Notes
select tests.as_user(:'ada');
select throws_ok(
  format('insert into public.notes (user_id, document_id, title) values (%L, %L, %L)', :'ada', :'bob_doc', 'x'),
  '23503', null, 'a note cannot be linked to someone else''s document'
);
select throws_ok(
  format('insert into public.notes (user_id, title) values (%L, %L)', :'bob', 'forged'),
  '42501', null, 'a user cannot create notes for someone else'
);
insert into public.notes (user_id, document_id, title, content, is_pinned) values (:'ada', :'doc', 'Mitosis', 'Prophase, metaphase…', true);
select is(
  (select title from public.notes where search @@ plainto_tsquery('simple', 'metaphase')),
  'Mitosis', 'notes are full-text searchable'
);

-- Flashcards
insert into public.flashcard_decks (id, user_id, document_id, title) values ('00000000-0000-0000-0000-0000000000d1', :'ada', :'doc', 'Cells');
insert into public.flashcards (id, deck_id, user_id, front, back) values
  ('00000000-0000-0000-0000-0000000000e1', '00000000-0000-0000-0000-0000000000d1', :'ada', 'ATP?', 'Energy currency');
select is((select card_count from public.flashcard_decks where id = '00000000-0000-0000-0000-0000000000d1'), 1, 'card_count is maintained');
select throws_ok(
  $$update public.flashcards set due_at = now() + interval '1 year'$$,
  '42501', null, 'the schedule can only be changed through review_flashcard'
);
select lives_ok(
  $$select public.review_flashcard('00000000-0000-0000-0000-0000000000e1', 3::smallint, 'review', now() + interval '3 days', 3.2, 5.1, 3, 4200)$$,
  'a user can record a review'
);
select results_eq(
  $$select state::text, reps, scheduled_days from public.flashcards where id = '00000000-0000-0000-0000-0000000000e1'$$,
  $$values ('review', 1, 3)$$,
  'the review updates the card schedule'
);
select is((select count(*)::int from public.flashcard_reviews), 1, 'the review is logged');

-- Deleting the document: chats go with it, study material stays
reset role;
insert into public.conversations (id, user_id, document_id, title) values ('00000000-0000-0000-0000-0000000000f1', :'ada', :'doc', 'Chat');
insert into public.messages (conversation_id, user_id, role, content) values
  ('00000000-0000-0000-0000-0000000000f1', :'ada', 'user', 'Explain mitosis'),
  ('00000000-0000-0000-0000-0000000000f1', :'ada', 'assistant', 'Mitosis is…');
select is((select message_count from public.conversations where id = '00000000-0000-0000-0000-0000000000f1'), 2, 'message_count is maintained');

delete from public.documents where id = :'doc';
select is((select count(*)::int from public.conversations where user_id = :'ada'), 0, 'document chats are deleted with the document');
select results_eq(
  $$select (select document_id from public.notes), (select document_id from public.quizzes), (select document_id from public.flashcard_decks)$$,
  $$values (null::uuid, null::uuid, null::uuid)$$,
  'notes, quizzes and decks survive document deletion, unlinked'
);

select * from finish();
rollback;
