import type { SupabaseClient } from '@supabase/supabase-js';

import type { Note, NoteDraft, NotesRepository } from '@/features/notes/domain/note';

import { check, currentUserId, unwrap } from './postgrest';

const NOTE_COLUMNS = 'id, title, content, is_pinned, document_id, source, updated_at';

type NoteRow = {
  id: string;
  title: string;
  content: string;
  is_pinned: boolean;
  document_id: string | null;
  source: 'manual' | 'ai';
  updated_at: string;
};

const toNote = (row: NoteRow): Note => ({
  id: row.id,
  title: row.title,
  content: row.content,
  isPinned: row.is_pinned,
  documentId: row.document_id,
  source: row.source,
  updatedAt: row.updated_at,
});

export class SupabaseNotesRepository implements NotesRepository {
  constructor(private readonly client: SupabaseClient) {}

  async list() {
    const rows = unwrap(
      await this.client
        .from('notes')
        .select(NOTE_COLUMNS)
        .order('is_pinned', { ascending: false })
        .order('updated_at', { ascending: false })
        .limit(1000),
    ) as NoteRow[];
    return rows.map(toNote);
  }

  async get(id: string) {
    return toNote(
      unwrap(await this.client.from('notes').select(NOTE_COLUMNS).eq('id', id).single()) as NoteRow,
    );
  }

  /** Creates or updates in one round trip; the id may be generated by the app (offline-friendly). */
  async save(draft: NoteDraft) {
    const fields = { title: draft.title, content: draft.content, is_pinned: draft.isPinned };
    if (draft.id) {
      const updated = unwrap(
        await this.client.from('notes').update(fields).eq('id', draft.id).select(NOTE_COLUMNS),
      ) as NoteRow[];
      if (updated[0]) return toNote(updated[0]);
    }
    const created = unwrap(
      await this.client
        .from('notes')
        .insert({
          ...fields,
          ...(draft.id ? { id: draft.id } : {}),
          user_id: await currentUserId(this.client),
          document_id: draft.documentId ?? null,
        })
        .select(NOTE_COLUMNS)
        .single(),
    ) as NoteRow;
    return toNote(created);
  }

  async remove(id: string) {
    check(await this.client.from('notes').delete().eq('id', id));
  }
}
